import os
import subprocess as sp
import sys

sys.path.append(os.path.abspath("."))
from frequent_words import *

FLATTENED_SEQUENCE = "ATGAATCCAAATCAGAAAATAATAACCATTGGATCAATCTGTATGGTAGTCGGAATAATTAGCCTAATATTGCAAATAGGGAATATTATCTCAATATGGATTAGCCATTCAATTCAAACTGGAAGTCAAAACCATACTGGAATATGCAACCAAAGCATCATTACCTATAAAAATAGCACCTGGGTAAATCAAACATATGTTAATATTAGCAACACTAACGTTGTTGCTGGAAAAGGCACAACTTCAGTGATATTAGCCGGCAATTCATCTCTTTGTCCTATCCGTGGGTGGGCTATATACAGCAAAGATAACGGCATAAGAATTGGTTCCAAAGGAGATGTTTTTGTCATAAGAGAGCCTTTTATTTCATGTTCTCACTTGGAATGCAGGACTTTTTTTCTGACCCAAGGCGCCCTGTTGAATGACAAGCATTCAAATGGGACCGTTAAGGACAGAAGCCCTTATAGGGCCTTGATGAGCTGCCCTGTCGGTGAAGCTCCGTCCCCGTACAATTCAAGGTTTGAATCGGTTGCTTGGTCAGCAAGTGCATGTCATGATGGCATGGGCTGGCTAACAATCGGAATTTCTGGTCCAGATGATGAAGCAGTGGCTGTGTTAAAATACAACGGCATAATAACTGAAACCATAAAAAGTTGGAGGAAGAAAATATTGAGAACACAAGAGTCTGAATGTGTCTGTGTAAATGGTTCATGTTTTACTATAATGACCGACGGCCCGAGTGATGGCCAGGCCTCGTACAAAATTTTCAAGATCGAGAAGGGGAAGGTTACTAAATCAATAGAGTTGGATGCACCTAATTCTCACTACGAGGAATGTTCCTGTTACCCTGATACCGGCAAGGTGATGTGTGTGTGCAGAGACAATTGGCACGGTTCGAACCGACCATGGGTGTCTTTCGATCAAAATCTGGATTATCAAATAGGATACATCTGCAGTGGGGTTTTCGGTGACAATCCGCGTTCCAAAGATGGAAAAGGCAGCTGTGGTCCGGTGTATGTTGATGGAGCAAACGGAGTAAAGGGATTTTCATACAGGTATGGTAATGGTGTTTGGATAGGAAGGACTAAAAGTGACAGTTCCAGACAGGGGTTTGAGATGATTTGGGATCCTAATGGGTGGACAGAGACTGATAGTAATTTCTTTGTGAAACAAGATATAGTGGCTATGACTGATTGGTCAGGGTACAGCGGAAGTTTCGTTCAACATCCTGAGCTAACAGGGCTGGACTGTATGAGGCCTTGCTTCTGGGTTGAATTAATCAGGGGACGACCTAAAGAAAAAACAATCTGGACTAGTGGGAGCAGCATTTCTTTTTGTGGCGTGAATAGTGATACTGTAGACTGGTCTTGGCCAGACGGTGCCGAATTGCCATTCACCATTGACAAGTAG"


def test_fasta_reading_single():
    """ Make sure reading-in fasta file with a single sequence in it is okay """
    seq = retrieve_sequence("tests/AF250365.2.fna")
    assert seq == FLATTENED_SEQUENCE


def test_fasta_reading_two():
    """ Make sure reading-in fasta file with multiple sequences in it is okay """
    seq = retrieve_sequence("tests/AF250365.2_twice.fna")
    assert seq == FLATTENED_SEQUENCE


def test_pattern_count():
    """ Test counting of patterns in sequence """
    seq = "AATACGTATAGGGTACCCTGAATATATATGAC"
    assert pattern_count(seq, "AATA") == 2
    assert pattern_count(seq, "TATA") == 3


def test_frequent_words():
    """ Test finding the most prevalent kmer in a sequence """
    seq = "AATACGTATAGGGTACCCTGAATATATATGAC"
    ct_3 = frequent_words(seq, 3)
    assert ct_3 == set(["ATA"])

    ct_4 = frequent_words(seq, 4)
    assert ct_4 == set(["ATAT", "TATA"])


def test_script():
    """ Test out the entire script """
    answer = {"AAAAT", "AAATA", "AATAT", "ATGTT", "ATTCA", "CTGGA", "GGAAT", "TCAAA", "TGAAT", "TGATG", "TGTGT", "TTCAA"}
    cmd = "python frequent_words.py -f tests/AF250365.2.fna -k 5"
    results = sp.run(cmd, stdout=sp.PIPE, stderr=sp.PIPE, shell=True)
    stdout = results.stdout.decode().strip()
    max_kmers = set(stdout.split("\n"))
    assert answer == max_kmers